name: observable
version: 0.22.3-dev
author: Dart Team <misc@dartlang.org>
description: Support for marking objects as observable
homepage: https://github.com/google/observable
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  collection: ^1.11.0
  dart_internal: ^0.2.0
  meta: ^1.0.4
  quiver: '>=0.24.0 <3.0.0'

dev_dependencies:
  build_runner: '>=0.8.0 <2.0.0'
  build_test: ^0.10.0
  build_web_compilers: '>=0.3.1 <3.0.0'
  dart_style: ^1.0.9
  pedantic: ^1.4.0
  test: ^1.3.0
